openapi: 3.1.0
info:
  title: Museum API
  version: 1.0.0
  description: Example museum API for Claude Desktop integration
servers:
  - url: https://redocly.com/_mock/demo/openapi/museum-api
paths:
  /museum-hours:
    get:
      summary: Get museum hours
      operationId: getMuseumHours
      parameters:
        - name: date
          in: query
          schema:
            type: string
            format: date
          description: Specific date to get hours for
      responses:
        '200':
          description: Museum hours for the specified date
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string
                    format: date
                  hours:
                    type: string
                  isOpen:
                    type: boolean
  /special-events:
    get:
      summary: List special events
      operationId: listSpecialEvents
      parameters:
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of special events
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    location:
                      type: string
                    date:
                      type: string
                      format: date
                    price:
                      type: number
    post:
      summary: Create special event
      operationId: createSpecialEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                location:
                  type: string
                date:
                  type: string
                  format: date
                price:
                  type: number
              required: [name, location, date, price]
      responses:
        '201':
          description: Event created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
security:
  - BasicAuth: []
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic